name: "vcf_pca_plink"

description: Preprocess and prune variants from reference data (such as 1000G) to perform PCA
keywords:
  - vcf
  - bcf
  - plink
  - prune
  - indep

modules:
  - bcftools/norm
  - bcftools/annotate
  - bcftools/index
  - plink/bcf
  - plink/indep
  - plink/extract

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - ch_vcf:
      type: file
      description: |
        VCF files and their indices that should be concatenated
        Structure: [ meta, vcf, tbi ]
  - ch_reference:
      type: file
      description: |
        Reference genome and its index file
        Structure: [ fasta, fai ]

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - bed:
      type: file
      description: PLINK binary biallelic genotype table
      pattern: "*.{bed}"
  - bim:
      type: file
      description: PLINK extended MAP file
      pattern: "*.{bim}"
  - fam:
      type: file
      description: PLINK sample information file
      pattern: "*.fam"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@atrigila"
