name: "plink_recode"
description: Recodes plink bfiles into a new text fileset applying different modifiers
keywords:
  - recode
tools:
  - "plink":
      description: "Whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner."
      homepage: "https://www.cog-genomics.org/plink"
      documentation: "https://www.cog-genomics.org/plink/1.9/data#recode"
      tool_dev_url: "https://www.cog-genomics.org/plink/1.9/dev"
      doi: ""
      licence: "['GPL']"

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  #
  - bed:
      type: file
      description: PLINK binary biallelic genotype table file
      pattern: "*.{bed}"
  - bim:
      type: file
      description: PLINK extended MAP file
      pattern: "*.{bim}"
  - fam:
      type: file
      description: PLINK sample information file
      pattern: "*.{fam}"

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  #
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - ped:
      type: file
      description: PLINK/MERLIN/Haploview text pedigree + genotype table file
      pattern: "*.{ped}"
  - map:
      type: file
      description: PLINK text fileset variant information file
      pattern: "*.{map}"
  - txt:
      type: file
      description: Text file
      pattern: "*.{txt}"
  - raw:
      type: file
      description: Additive + dominant component file
      pattern: "*.{raw}"
  - traw:
      type: file
      description: Variant-major additive component file
      pattern: "*.{traw}"
  - beagle-dat:
      type: file
      description: Single BEAGLE unphased genotype file
      pattern: "*.{beagle.dat}"
  - chr-dat:
      type: file
      description: BEAGLE unphased genotype and variant information files
      pattern: "*.{*.chr-*.dat}"
  - chr-map:
      type: file
      description: BEAGLE variant information files
      pattern: "*.{*chr-*.map}"
  - geno:
      type: file
      description: BIMBAM genotype file
      pattern: "*.{recode.geno.txt}"
  - pheno:
      type: file
      description: BIMBAM phenotype file
      pattern: "*.{recode.pheno.txt}"
  - pos:
      type: file
      description: BIMBAM variant position file
      pattern: "*.{recode.pos.txt}"
  - phase:
      type: file
      description: fastPHASE format
      pattern: "*.{recode.phase.inp}"
  - info:
      type: file
      description: Haploview map file
      pattern: "*.{info}"
  - lgen:
      type: file
      description: PLINK long-format genotype file
      pattern: "*.{lgen}"
  - list:
      type: file
      description: Genotype list file
      pattern: "*.{list}"
  - gen:
      type: file
      description: Oxford genotype file format
      pattern: "*.{gen}"
  - genz:
      type: file
      description: Compressed Oxford genotype file format
      pattern: "*.{genz}"
  - sample:
      type: file
      description: Oxford sample information file
      pattern: "*.{sample}"
  - rlist:
      type: file
      description: Rare genotype list file
      pattern: "*.{rlist}"
  - strctin:
      type: file
      description: Structure-format file
      pattern: "*.{strct_in}"
  - tped:
      type: file
      description: Transposed text PED file
      pattern: "*.{tped}"
  - tfam:
      type: file
      description: Transposed text FAM file
      pattern: "*.{tfam}"
  - vcf:
      type: file
      description: Variant calling file (VCF)
      pattern: "*.{vcf}"
  - vcfgz:
      type: file
      description: Compressed variant calling file (VCF)
      pattern: "*.{vcf.gz}"

authors:
  - "@atrigila"
