name: "dream_differential"
description: Runs a differential expression analysis with dream() from variancePartition R package
keywords:
  - differential
  - expression
  - rnaseq
  - dream
  - variancepartition
tools:
  - "dream":
      description: "Differential expression for repeated measures"
      homepage: "https://www.bioconductor.org/packages/release/bioc/html/variancePartition.html"
      documentation: "https://www.bioconductor.org/packages/release/bioc/manuals/variancePartition/man/variancePartition.pdf"
      tool_dev_url: "https://github.com/DiseaseNeuroGenomics/variancePartition"
      doi: "10.1093/bioinformatics/btaa687"
      licence: ["LGPL >=3"]
      identifier: null
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing run and contrast information. This can be used at the
          workflow level to pass optional parameters to the module, e.g.
          [
            contrast_id: 'treatment_mCherry_hND6',
            contrast_variable: 'treatment',
            contrast_reference: 'mCherry',
            contrast_target: 'hND6',
            blocking_factors: 'sample_number'
          ]
          Plus mandatory `id` and other fields created along the run.
    - samplesheet:
        type: file
        description: Sample sheet file containing sample metadata.
    - counts:
        type: file
        description: |
          Raw TSV or CSV format expression matrix with count data by row and samples
          by column
output:
  - results:
      - meta:
          type: file
          description: TSV-format table of differential expression information as output
            by dream
          pattern: "*.limma.results.tsv"
      - "*.dream.results.tsv":
          type: file
          description: TSV-format table of differential expression information as output
            by Limma
          pattern: "*.limma.results.tsv"
  - md_plot:
      - meta:
          type: file
          description: Limma mean difference plot
          pattern: "*.mean_difference.png"
      - "*.limma.mean_difference.png":
          type: file
          description: Limma mean difference plot
          pattern: "*.mean_difference.png"
  - rdata:
      - meta:
          type: file
          description: Serialised MArrayLM object
          pattern: "*.MArrayLM.limma.rds"
      - "*.MArrayLM.limma.rds":
          type: file
          description: Serialised MArrayLM object
          pattern: "*.MArrayLM.limma.rds"
  - model:
      - meta:
          type: file
          description: TXT-format limma model
          pattern: "*.limma.model.tsv"
      - "*.limma.model.txt":
          type: file
          description: TXT-format limma model
          pattern: "*.limma.model.tsv"
  - session_info:
      - meta:
          type: file
          description: dump of R SessionInfo
          pattern: "*.log"
      - "*.R_sessionInfo.log":
          type: file
          description: dump of R SessionInfo
          pattern: "*.log"
  - normalised_counts:
      - meta:
          type: file
          description: normalised TSV format expression matrix with probes by row and samples by column
          pattern: "*.normalised_counts.tsv"
      - "*.normalised_counts.tsv":
          type: file
          description: normalised TSV format expression matrix with probes by row and samples by column
          pattern: "*.normalised_counts.tsv"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@alanmmobbs03"
maintainers:
  - "@alanmmobbs03"
